services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Lemonmind\SaveStringReplaceBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]
